In [95]:
import plotly.express as px
import pandas as pd

# 1. Creamos un DataFrame con los datos de la imagen
data = {
    'x': [0.8, 1.0, 1.2, 0.8, 1.2, 4.0, 3.8, 4.2, 3.8, 4.2, 4.4, 4.4, 3.2, 3.2, 3.8, 3.5, 4.0, 4.0],
    'y': [0.8, 1.0, 0.8, 1.2, 1.2, 3.0, 2.8, 2.8, 3.2, 3.2, 2.8, 3.2, 0.4, 0.7, 0.5, 1.0, 1.0, 0.7],
    'clase': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]
}

df = pd.DataFrame(data)

# Convertimos 'clase' a string para que Plotly la trate como categoría discreta (colores distintos)
df['clase'] = df['clase'].astype(str)

# 2. Creamos el gráfico de dispersión 3D
fig = px.scatter_3d(
    df, 
    x='x', 
    y='y', 
    z='clase',
    color='clase',
    title="Visualización 3D con Plotly",
    labels={'clase': 'Clase / Eje Z'},
    color_discrete_sequence=px.colors.qualitative.Bold
)

# 3. Ajustamos el tamaño de los puntos
fig.update_traces(marker=dict(size=5))

# Mostramos el gráfico
fig.show()

In [96]:
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

# 1. Datos de entrenamiento (Dataset original)
data = {
    'x': [0.8, 1.0, 1.2, 0.8, 1.2, 4.0, 3.8, 4.2, 3.8, 4.2, 4.4, 4.4, 3.2, 3.2, 3.8, 3.5, 4.0, 4.0],
    'y': [0.8, 1.0, 0.8, 1.2, 1.2, 3.0, 2.8, 2.8, 3.2, 3.2, 2.8, 3.2, 0.4, 0.7, 0.5, 1.0, 1.0, 0.7],
    'clase': [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]
}
df = pd.DataFrame(data)
df['clase'] = df['clase'].astype(str)

# 2. Creamos la figura base con los puntos de entrenamiento
fig = px.scatter(
    df, x='x', y='y', color='clase',
    title="Ubicación del Punto P(3, 2) en el Espacio de Clases",
    labels={'clase': 'Clase de Entrenamiento'},
    template="plotly_white"
)

# 3. Añadimos el punto P=(3, 2) manualmente con un marcador especial
fig.add_trace(
    go.Scatter(
        x=[3], y=[2],
        mode='markers+text',
        marker=dict(size=18, color='gold', symbol='star', line=dict(width=2, color='black')),
        name='Punto P (Entrada)',
        text=["P(3, 2)"],
        textposition="top center"
    )
)

# Mejoramos el diseño
fig.update_traces(marker=dict(size=12))
fig.show()

In [97]:
import math
import pandas as pd

# 1. Definimos el punto de entrada P
P = (3, 2)

# 2. Lista de patrones (x, y, clase) extraídos de la imagen
patrones = [
    (0.8, 0.8, 1), (1.0, 1.0, 1), (1.2, 0.8, 1), (0.8, 1.2, 1), (1.2, 1.2, 1),
    (4.0, 3.0, 2), (3.8, 2.8, 2), (4.2, 2.8, 2), (3.8, 3.2, 2), (4.2, 3.2, 2), (4.4, 2.8, 2), (4.4, 3.2, 2),
    (3.2, 0.4, 3), (3.2, 0.7, 3), (3.8, 0.5, 3), (3.5, 1.0, 3), (4.0, 1.0, 3), (4.0, 0.7, 3)
]

distancias_lista = []

# 3. Ciclo for para calcular la distancia a cada punto X_n
print(f"{'Punto':<10} | {'Coordenadas':<15} | {'Clase':<6} | {'Distancia a P':<15}")
print("-" * 55)

for i, punto in enumerate(patrones, 1):
    px, py, clase = punto
    
    # Cálculo de distancia euclidiana
    distancia = math.sqrt((px - P[0])**2 + (py - P[1])**2)
    
    # Guardamos para un análisis posterior
    distancias_lista.append({
        'Punto': f'X{i}',
        'x': px,
        'y': py,
        'clase': clase,
        'distancia': distancia
    })
    
    print(f"X{i:<8} | ({px:>3}, {py:>3})     | {clase:<6} | {distancia:.4f}")

# 4. (Opcional) Encontrar el punto más cercano
df_distancias = pd.DataFrame(distancias_lista)
mas_cercano = df_distancias.loc[df_distancias['distancia'].idxmin()]

print("\n" + "="*55)
print(f"El punto más cercano es {mas_cercano['Punto']} (Clase {mas_cercano['clase']}) "
      f"con una distancia de {mas_cercano['distancia']:.4f}")

Punto      | Coordenadas     | Clase  | Distancia a P  
-------------------------------------------------------
X1        | (0.8, 0.8)     | 1      | 2.5060
X2        | (1.0, 1.0)     | 1      | 2.2361
X3        | (1.2, 0.8)     | 1      | 2.1633
X4        | (0.8, 1.2)     | 1      | 2.3409
X5        | (1.2, 1.2)     | 1      | 1.9698
X6        | (4.0, 3.0)     | 2      | 1.4142
X7        | (3.8, 2.8)     | 2      | 1.1314
X8        | (4.2, 2.8)     | 2      | 1.4422
X9        | (3.8, 3.2)     | 2      | 1.4422
X10       | (4.2, 3.2)     | 2      | 1.6971
X11       | (4.4, 2.8)     | 2      | 1.6125
X12       | (4.4, 3.2)     | 2      | 1.8439
X13       | (3.2, 0.4)     | 3      | 1.6125
X14       | (3.2, 0.7)     | 3      | 1.3153
X15       | (3.8, 0.5)     | 3      | 1.7000
X16       | (3.5, 1.0)     | 3      | 1.1180
X17       | (4.0, 1.0)     | 3      | 1.4142
X18       | (4.0, 0.7)     | 3      | 1.6401

El punto más cercano es X16 (Clase 3) con una distancia de 1.1180


In [98]:
import numpy as np
from collections import Counter

# 1. Configuración de datos y Punto P
P = np.array([4.2, 1.8])
k = 5

datos = np.array([
    [0.8, 0.8, 1], [1.0, 1.0, 1], [1.2, 0.8, 1], [0.8, 1.2, 1], [1.2, 1.2, 1],
    [4.0, 3.0, 2], [3.8, 2.8, 2], [4.2, 2.8, 2], [3.8, 3.2, 2], [4.2, 3.2, 2], [4.4, 2.8, 2], [4.4, 3.2, 2],
    [3.2, 0.4, 3], [3.2, 0.7, 3], [3.8, 0.5, 3], [3.5, 1.0, 3], [4.0, 1.0, 3], [4.0, 0.7, 3]
])

# 2. Cálculo de Distancias Euclidianas
coords = datos[:, :2]
clases = datos[:, 2]
distancias = np.linalg.norm(coords - P, axis=1)

# 3. Obtener los 5 vecinos más cercanos
indices_k = np.argsort(distancias)[:k]
vecinos_dist = distancias[indices_k]
vecinos_clases = clases[indices_k]

# 4. Cálculo de Pesos Individuales y Acumulados (Mk-NN)
pesos_por_clase = {}
print(f"--- Desglose de Pesos Individuales (k={k}) ---")
print(f"{'Vecino':<10} | {'Clase':<6} | {'Distancia (d)':<15} | {'Peso (1/d)':<15}")
print("-" * 55)

for i in range(k):
    c = int(vecinos_clases[i])
    d = vecinos_dist[i]
    
    # Cálculo del 'valorcito' o peso individual
    peso_individual = 1 / d if d != 0 else 1e10
    
    # Acumular en la clase correspondiente
    pesos_por_clase[c] = pesos_por_clase.get(c, 0) + peso_individual
    
    print(f"Vecino {i+1:<3} | {c:<6} | {d:<15.4f} | {peso_individual:<15.4f}")

# 5. Resultados Finales
print("\n--- Sumatoria Final de Pesos por Clase ---")
for clase, peso_total in pesos_por_clase.items():
    print(f"Clase {clase}: {peso_total:.4f}")

# Decisión final
clase_ganadora = max(pesos_por_clase, key=pesos_por_clase.get)
print(f"\nResultado Mk-NN: El punto se asigna a la Clase {clase_ganadora}")

--- Desglose de Pesos Individuales (k=5) ---
Vecino     | Clase  | Distancia (d)   | Peso (1/d)     
-------------------------------------------------------
Vecino 1   | 3      | 0.8246          | 1.2127         
Vecino 2   | 2      | 1.0000          | 1.0000         
Vecino 3   | 2      | 1.0198          | 0.9806         
Vecino 4   | 3      | 1.0630          | 0.9407         
Vecino 5   | 2      | 1.0770          | 0.9285         

--- Sumatoria Final de Pesos por Clase ---
Clase 3: 2.1534
Clase 2: 2.9091

Resultado Mk-NN: El punto se asigna a la Clase 2


In [99]:
import numpy as np
import pandas as pd
from collections import Counter

# 1. Configuración de datos
P = np.array([4.2, 1.8])
k = 5

# Matriz de entrenamiento: [x, y, clase]
datos = np.array([
    [0.8, 0.8, 1], [1.0, 1.0, 1], [1.2, 0.8, 1], [0.8, 1.2, 1], [1.2, 1.2, 1],
    [4.0, 3.0, 2], [3.8, 2.8, 2], [4.2, 2.8, 2], [3.8, 3.2, 2], [4.2, 3.2, 2], [4.4, 2.8, 2], [4.4, 3.2, 2],
    [3.2, 0.4, 3], [3.2, 0.7, 3], [3.8, 0.5, 3], [3.5, 1.0, 3], [4.0, 1.0, 3], [4.0, 0.7, 3]
])

# 2. Cálculo de Distancias
coords = datos[:, :2]
clases = datos[:, 2]

# Distancia Euclidiana: sqrt((x-px)^2 + (y-py)^2)
distancias = np.linalg.norm(coords - P, axis=1)

# 3. Selección de los k vecinos más cercanos
indices_ordenados = np.argsort(distancias)
k_indices = indices_ordenados[:k]

vecinos_dist = distancias[k_indices]
vecinos_clases = clases[k_indices]

# --- ALGORITMO 1: k-NN (Votación simple) ---
conteo_votos = Counter(vecinos_clases)
clase_knn = conteo_votos.most_common(1)[0][0]

# --- ALGORITMO 2: Mk-NN (Votación ponderada) ---
pesos_por_clase = {}
for c, d in zip(vecinos_clases, vecinos_dist):
    # Evitar división por cero si d=0
    peso = 1 / d if d != 0 else 1e10
    pesos_por_clase[c] = pesos_por_clase.get(c, 0) + peso

clase_mknn = max(pesos_por_clase, key=pesos_por_clase.get)

# 4. Mostrar Resultados
print(f"Análisis para P = {P} con k = {k}")
print("-" * 40)
print(f"Vecinos seleccionados (Clase | Distancia):")
for i in range(k):
    print(f" - Clase {int(vecinos_clases[i])} | Dist: {vecinos_dist[i]:.4f}")

print("\n--- RESULTADOS ---")
print(f"Clasificación k-NN:   Clase {int(clase_knn)} (Votos: {dict(conteo_votos)})")
print(f"Clasificación Mk-NN:  Clase {int(clase_mknn)}")
print("Pesos Mk-NN (1/d):")
for c, p in pesos_por_clase.items():
    print(f" - Clase {int(c)}: {p:.4f}")

Análisis para P = [4.2 1.8] con k = 5
----------------------------------------
Vecinos seleccionados (Clase | Distancia):
 - Clase 3 | Dist: 0.8246
 - Clase 2 | Dist: 1.0000
 - Clase 2 | Dist: 1.0198
 - Clase 3 | Dist: 1.0630
 - Clase 2 | Dist: 1.0770

--- RESULTADOS ---
Clasificación k-NN:   Clase 2 (Votos: {np.float64(3.0): 2, np.float64(2.0): 3})
Clasificación Mk-NN:  Clase 2
Pesos Mk-NN (1/d):
 - Clase 3: 2.1534
 - Clase 2: 2.9091


# Parte 2

In [100]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

conjunto_de_datos = pd.read_csv("datos.csv")
X = conjunto_de_datos.iloc[:, 1:3].values
Y = conjunto_de_datos.iloc[:, 3].values

X, Y

(array([[4.4e+01, 7.2e+04],
        [2.7e+01, 4.8e+04],
        [3.0e+01, 5.4e+04],
        [3.8e+01, 6.1e+04],
        [4.0e+01,     nan],
        [3.5e+01, 5.8e+04],
        [    nan, 5.2e+04],
        [4.8e+01, 7.9e+04],
        [5.0e+01, 8.3e+04],
        [3.7e+01, 6.7e+04]]),
 array(['No', 'Si', 'No', 'No', 'Si', 'Si', 'No', 'Si', 'No', 'Si'],
       dtype=object))

In [101]:
conjunto_de_datos

,Pais,fecha,Salario,Seleccionado
0,Francia,44.0,72000.0,No
1,Mexico,27.0,48000.0,Si
2,Alemania,30.0,54000.0,No
3,Mexico,38.0,61000.0,No
4,Alemania,40.0,NaN,Si
5,Francia,35.0,58000.0,Si
6,Mexico,NaN,52000.0,No
7,Francia,48.0,79000.0,Si
8,Alemania,50.0,83000.0,No
9,Francia,37.0,67000.0,Si


In [102]:
from sklearn.impute import SimpleImputer

variable_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = variable_imputer.fit_transform(X)
X

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [103]:
from sklearn.preprocessing import StandardScaler

escalador_en_x = StandardScaler()
escalador_en_x.fit_transform(X)
X

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])